[default]
address = "127.0.0.1"
# secret_key = "2m/nGcyDPugFPW2Jod3wtTects1i6AhkEPtZW01fVL4==="

[default.shutdown]
ctrlc = true

[default.databases.sea_orm]
url = "mysql://root:@localhost/tellonym_clone"